stages:
    - test
    - deploy

defualt:
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
    retry: 2

tests:
    stage: test
    script:
        - bundle exec fastlane tests
    tags:
        - xcode-11.3

deploy_development:
    stage: deploy
    script:
        - bundle exec fastlane deployDev
    tags:
        - xcode-11.3
    only:
        - tags

deploy_staging:
    stage: deploy
    script:
        - bundle exec fastlane deployStg
    tags:
        - xcode-11.3
    only:
        - tags

deploy_production:
    stage: deploy
    script:
        - bundle exec fastlane deployProd
    tags:
        - xcode-11.3
    only:
        - tags        