stages:
    - test
    - deploy

default:
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash

tests:
    stage: test
    retry: 2
    script:
        - bundle exec fastlane tests
    tags:
        - xcode-11.3

deploy_development:
    stage: deploy
    retry: 2
    script:
        - bundle exec fastlane deployDev
    tags:
        - xcode-11.3
    only:
        - tags

deploy_staging:
    stage: deploy
    retry: 2
    script:
        - bundle exec fastlane deployStg
    tags:
        - xcode-11.3
    only:
        - tags

deploy_production:
    stage: deploy
    retry: 2
    script:
        - bundle exec fastlane deployProd
    tags:
        - xcode-11.3
    only:
        - tags        