disabled_rules:
    - identifier_name
    - weak_delegate
    - cyclomatic_complexity
    - closure_parameter_position
    - orphaned_doc_comment
    - todo
opt_in_rules:
    - force_unwrapping
excluded:
  - Carthage
  - Pods
  - .bundle
  - .idea
line_length: 125
large_tuple: 3
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
